apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mobigen

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - web-deployment.yaml
  - generator-deployment.yaml
  - builder-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: mobigen
  app.kubernetes.io/managed-by: kustomize

images:
  - name: mobigen/web
    newTag: latest
  - name: mobigen/generator
    newTag: latest
  - name: mobigen/builder
    newTag: latest
